---
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: custom-job
spec:
  image: zablondev/flink-job:latest
  flinkVersion: v1_20
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink-jobs/hello-world-job-1.0.jar
    parallelism: 1
    upgradeMode: stateless
  ingress:
    template: "localhost/{{name}}(/|$)(.*)"
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"