--- 
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: custom-job-ha
spec:
  image: zablondev/flink-job:latest
  flinkVersion: v1_20
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"

    s3.access.key: admin
    s3.secret.key: password
    s3.path.style.access: "true"

    state.backend: rocksdb
    state.backend.incremental: "true"
    state.checkpoints.dir: s3://flink-data/checkpoints
    state.savepoints.dir: s3://flink-data/savepoints

    high-availability.type: kubernetes
    high-availability.storageDir: s3://flink-data/ha
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          env:
            - name: ENABLE_BUILT_IN_PLUGINS
              value: "flink-s3-fs-presto-1.20.0.jar"
  job:
    jarURI: local:///opt/flink/examples/streaming/flink-hello-world-1.0.jar
    parallelism: 2
    upgradeMode: savepoint
    state: running
