---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kind-pv
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  hostPath:
    path: /files/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
  labels:
    app: minio-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: kind-pv
  resources:
    requests:
      storage: 8Gi
